Added; getFriendInvite, createFriendInvite, deleteFriendInvite.
rigwild/discord-self-bot-console pull request #62
Opened 2023-08-08 16:29 UTC by DeadLyBro

+ getFriendInvite()
+ createFriendInvite()
+ deleteFriendInvite()

getFriendInvite is returning your active invites.
createFriendInvite is giving Friend Invite for use 5 times. deleteFriendInvite is delete your last Friend Invite.

You can use the "code". (Length 8 char.)
E.g: https://discord.gg/AaBbcCDd

I hope you guys understand what I said here.

2023-08-08 16:32 UTC, DeadLyBro commented
I don't tried with "code" to `deleteFriendInvite()` , so i don't know if that is working for "code" delete. 
But I'm sure its deleting last one with that code.

2023-08-08 16:34 UTC, DeadLyBro commented
Ups, I'm so sorry its deleting all invites lol. I check it now.

2023-08-11 16:45 UTC, rigwild commented
Please also add types in https://github.com/rigwild/discord-self-bot-console/blob/main/types.d.ts

2023-08-11 17:34 UTC, DeadLyBro commented
```ts
getFriendInvite(): Promise<any>
createFriendInvite(): Promise<any>
deleteFriendInvite(): Promise<any>
```

Is it ok like this? @rigwild

2023-08-11 17:42 UTC, rigwild commented
Yes it's ok

Also add to delete 1 invite 

> Ups, I'm so sorry its deleting all invites lol. I check it now.

2023-08-11 17:42 UTC, DeadLyBro commented
> Also add to delete 1 invite
> 
> > Ups, I'm so sorry its deleting all invites lol. I check it now.

Idk how to do that, can you try it?

2023-08-11 17:50 UTC, DeadLyBro commented
Ok i found it.

2023-08-11 17:55 UTC, DeadLyBro commented
I hope its work.

2023-08-11 17:59 UTC, DeadLyBro commented
Oh no, I tried now... deleteFriendInvite(code) is deleting all invites again...

2023-08-11 18:00 UTC, DeadLyBro commented
can you help me

2023-08-11 18:22 UTC, DeadLyBro commented
We are getting a friend invite link with that code so you can use only like this; https://discord.gg/AaBbcCDd

2023-08-11 18:23 UTC, DeadLyBro commented
![image](https://github.com/rigwild/discord-self-bot-console/assets/31214077/bc5ba41f-d97c-4a4a-b4bd-2e4ae1dab0bc)

2023-08-11 18:25 UTC, rigwild commented
Ok but what are you achieving? Inviting what? To a guild? I'm confused as to what this does

2023-08-11 18:27 UTC, DeadLyBro commented
No, with this invite link, someone can add a friend you without asking.

2023-08-11 18:37 UTC, DeadLyBro commented
Deleting deleteFriendInvite because not working...

2023-08-11 18:42 UTC, rigwild commented on index.js
> +
```suggestion
    getFriendDirectInviteLinks: () => apiCall(`/users/@me/invites`),
    createFriendDirectInviteLink: () => apiCall(`/users/@me/invites`, null, 'POST'),
    deleteAllFriendDirectInviteLinks: () => apiCall(`/users/@me/invites`, null, 'DELETE'),
```

2023-08-11 18:42 UTC, DeadLyBro commented
![image](https://github.com/rigwild/discord-self-bot-console/assets/31214077/d9679b0c-c989-4391-b1e2-4514d4c75d94)
I found this on API... Gonna try it.

2023-08-11 18:43 UTC, rigwild commented on types.d.ts
> +  deleteFriendInvite(code: string): Promise<any>
```suggestion
  getFriendDirectInviteLinks(): Promise<any>
  createFriendDirectInviteLink(): Promise<any>
  deleteAllFriendDirectInviteLinks(): Promise<any>
```

2023-08-11 18:44 UTC, rigwild commented
I looked on the web and found out that it's not a supported feature by discord and was abandonned quickly after they added it

But looks like it still works, though the invite expires after 7d or 5 uses maximum

For delete 1 invite I tried to call `DELETE /invites/code` which is the one they call to delete invite link in guilds, but does not work

Maybe they never implemented it

2023-08-11 18:46 UTC, DeadLyBro commented
Yeah I think so. You can search on web; Discord Friend Invite. 
There is a video channel named No Text To Speech.

2023-08-11 20:49 UTC, rigwild requested changes

2023-08-11 20:49 UTC, rigwild commented on index.js
> +    deleteFriendInvites: () => apiCall(`/users/@me/invites`, null, 'DELETE'),
```suggestion
    getDirectFriendInviteLinks: () => apiCall(`/users/@me/invites`),
    createDirectFriendInviteLink: () => apiCall(`/users/@me/invites`, null, 'POST'),
    deleteDirectFriendInviteLinks: () => apiCall(`/users/@me/invites`, null, 'DELETE'),
```

2023-08-11 20:49 UTC, rigwild commented on types.d.ts
> +  deleteFriendInvites(): Promise<any>
```suggestion
  getDirectFriendInviteLinks(): Promise<any>
  createDirectFriendInviteLink(): Promise<any>
  deleteDirectFriendInviteLinks(): Promise<any>
```

2023-08-11 20:50 UTC, rigwild approved these changes

2023-08-11 20:50 UTC, merged

2023-08-11 20:50 UTC, rigwild commented
Thanks!